# Generated by Django 3.0.14 on 2022-06-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciity',
            new_name='City',
        ),
    ]
